<?php

/*
 * This file is part of BedrockProtocol.
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

declare(strict_types=1);

namespace pocketmine\network\mcpe\protocol;

/**
 * This trait provides default implementations for all packet handlers, so that you don't have to manually write
 * handlers for every single packet even if you don't care about them.
 *
 * This file is automatically generated. Do not edit it manually.
 */
trait PacketHandlerDefaultImplTrait{

%s
}
